gfx/env/familyguyup.tga
gfx/env/familyguydn.tga
gfx/env/familyguylf.tga
gfx/env/familyguyrt.tga
gfx/env/familyguyft.tga
gfx/env/familyguybk.tga
models/familyguy_kitchen.mdl
models/familyguy_couch.mdl
models/familyguy_bed.mdl
models/familyguy_policecar.mdl
models/familyguy_toilet.mdl
models/familyguy_flag.mdl
models/familyguy_bot.mdl
models/familyguy_tub.mdl
overviews/cs_familyguy.bmp
overviews/cs_familyguy.txt