maps/surf_lostzone_2.res
maps/surf_lostzone_2.txt
sprites/spr1n/digits/kzblt/x0.spr
sprites/spr1n/digits/kzblt/x1.spr
sprites/spr1n/digits/kzblt/x2.spr
sprites/spr1n/digits/kzblt/x3.spr
sprites/spr1n/digits/kzblt/x4.spr
sprites/spr1n/digits/kzblt/x5.spr
sprites/spr1n/digits/kzblt/x6.spr
sprites/spr1n/digits/kzblt/x7.spr
sprites/spr1n/digits/kzblt/x8.spr
sprites/spr1n/digits/kzblt/x9.spr
sprites/spr1n/digits/kznum/x0.spr
sprites/spr1n/digits/kznum/x1.spr
sprites/spr1n/digits/kznum/x2.spr
sprites/spr1n/digits/kznum/x3.spr
sprites/spr1n/digits/kznum/x4.spr
sprites/spr1n/digits/kznum/x5.spr
sprites/spr1n/digits/kznum/x6.spr
sprites/spr1n/digits/kznum/x7.spr
sprites/spr1n/digits/kznum/x8.spr
sprites/spr1n/digits/kznum/x9.spr
sprites/spr1n/digits/kzold/x0.spr
sprites/spr1n/digits/kzold/x1.spr
sprites/spr1n/digits/kzold/x2.spr
sprites/spr1n/digits/kzold/x3.spr
sprites/spr1n/digits/kzold/x4.spr
sprites/spr1n/digits/kzold/x5.spr
sprites/spr1n/digits/kzold/x6.spr
sprites/spr1n/digits/kzold/x7.spr
sprites/spr1n/digits/kzold/x8.spr
sprites/spr1n/digits/kzold/x9.spr